### PR TITLE
CSS function recursion

### LINKED ISSUE #390: Allow nested functions for css prop
Glamorous accepts an array for the `css` prop, which may contain nested arrays of styles. Those styles may be callback functions in order to access the theme:

`<Div css={ [myStyle1, myStyle2, ({ theme}) => myStyle3] } />`

We currently do not support recursion for the callback's results: https://github.com/paypal/glamorous/blob/d9560fa6ac9afcdd214ce211f8533280beb7062c/src/get-glamor-classname.js#L79-L86

Would you accept a PR to adjust this? I'm working to make styles functionally composeable, and it would be great if I could return an array with further callback functions!

### PR DESCRIPTION
**Pull request by quicksnap**
This approach simply unwinds functions until it gets a non-function, then recurses normally.

**What**:

Style function recursion. Closes #390 

**Checklist**:

* [ ] Documentation
* [x] Tests
* [x] Ready to be merged 
* [ ] Added myself to contributors table

### CODE REVIEW

**Comment by quicksnap** [comment]
Ok, added a test and it's working good! Ready to go.

**Comment by quicksnap** [comment]
Neat! Thanks for merging so quickly. How often do you cut releases?

**Comment by kentcdodds** [comment]
Immediately and automatically :) This was published a few minutes ago as `4.12.0` :+1:

**Comment by kentcdodds** [comment]
Thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the `other/MAINTAINING.md` and `CONTRIBUTING.md` files (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Comment by quicksnap** [comment]
💃 💃 💃 💃 💃 💃 💃 💃 💃

**Pull request merged**
