### PR TITLE
docs(logo): change the logo

### PR DESCRIPTION
**Pull request by kentcdodds**
ref #1

**What**: This changes the logo

**Why**: Because things discussed in #1 (copyright issues and such)

**How**: Help from friends like @Connorelsea and @markdalgleish :clap:

### CODE REVIEW

**Comment by kentcdodds** [comment]
I would really like to have an SVG version of both of these. And actually, now that I think of it, I want to see a version of the full one with that gradient too 🤔

**Comment by Connorelsea** [comment]
I'm not too familiar with editing SVGs, but the gradient is from #e63a5c to #f87880 if someone would like to try it out.

**Comment by kentcdodds** [comment]
Could you try it on [this](https://codesandbox.io/s/D9O2NGE9B) @Connorelsea?

**Comment by paulmolluzzo** [comment]
@kentcdodds Please tell me I can get this as a sticker! 🙏 🙏 🙏

**Comment by kentcdodds** [comment]
YES!

**Pull request merged**
