### PR TITLE
fix(typescript): Fixed issue where glamorous accepted invalid functions

### LINKED ISSUE #212: Typescript: Glamorous Component Factory is not as strict as intended
- `glamorous` version: 3.23.5

Problem description:

Currently there are a number ways to use glamorous with typescript where you have incomplete typesafety.

We've started coming across these with a number of our components and internal glamorous helpers.

Suggested solution:

Improve/fix the typings and add a test file for things that should fail with typescript.

I've got a WIP pr at the following link, I'm just waiting on an issue I've raised on the typescript repo before finishing this off.

https://github.com/luke-john/glamorous/pull/1

I may not get a chance to do that for a few days so opening this issue in the meantime in case anyone else hits up against this.

### PR DESCRIPTION
**Pull request by luke-john**
BREAKING CHANGE: Glamorous function arguments will no longer be untyped which will break on any code
that was returning things that are not valid style objects.

closes #212

**What**:

Fixes issue where Partials accept arbitary functions, which resulted in glamorous accepting methods
of any shape.

**Why**:

Currently there are a number ways to use glamorous with typescript where you have incomplete typesafety.

We've started coming across these with a number of our components and internal glamorous helpers.

**How**:

Updated the typescript typing for glamorous component factories arguments to not accept arbitrary functions.

Also added tests for things that should fail with the typings.

**Checklist**:
- [ ] Documentation N/A
- [x] Tests
- [x] Code complete
- [ ] Added myself to contributors table N/A
- [x] Followed the commit message format

As part of tracing down why the tests were passing for invalid things it was a bit hard due to mismatches between namings in the typings and glamorouses own code/documentation.  I ended up refactoring a bunch of that at the same time which I'll put up in it's own pr following this.

Also @kentcdodds I've added a test to the `src/tests` folder which compiles the typescript and expects the failure output to match the snapshotted failures.

I placed this in there to take advantage of the current jest setup, however would be happy to move that alongside the typings if you'd prefer.

### CODE REVIEW

**Comment by luke-john** [comment]
Also just a note, the use of the index signature kills autocomplete, though it looks like this hasn't worked for a while.

**Comment by kentcdodds** [comment]
I changed this to point to the `next` branch so we can group a few breaking changes together (once something lands into master it's autoreleased).

Could we get one of the TypeScript folks to give this a look?

**Comment by luke-john** [comment]
Had a chance to play around a bit more with possible type structures and came up with the following which only loses autocomplete on StyleFunctions, but if you break them out you will still be able to get autocomplete.

Won't likely be able to put up an alternative pr today so if this is causing issues for anyone else feel free to pick it up :).

[typescript playground example](http://www.typescriptlang.org/play/#src=interface%20StylesComplete%20%7B%0D%0A%20%20propA%3A%20'letter%20a'%20%7C%20'a'%2C%0D%0A%20%20propB%3A%20'letter%20b'%20%7C%20'b'%2C%0D%0A%7D%0D%0A%0D%0Ainterface%20StylesLossy%20%7B%0D%0A%20%20%5Bkey%3A%20string%5D%3A%20string%20%7C%20undefined%20%7C%20Partial%3CStylesComplete%3E%2C%0D%0A%7D%0D%0A%0D%0Atype%20Styles%20%3D%0D%0A%20%20%26%20StylesComplete%0D%0A%20%20%26%20StylesLossy%0D%0A%0D%0Atype%20CorrectStyleFunction%20%3D%0D%0A%20%20(prop%3A%20string)%20%3D%3E%20Partial%3CStyles%3E%0D%0A%0D%0Atype%20LessCorrectButEasierStyleFunction%20%3D%0D%0A%20%20(prop%3A%20string)%20%3D%3E%20Partial%3CStylesComplete%3E%0D%0A%0D%0Ainterface%20Styler%20%7B%0D%0A%20%20(mood%3A%20Partial%3CStyles%3E)%3A%20void%0D%0A%20%20(mood%3A%20CorrectStyleFunction)%3A%20void%0D%0A%7D%0D%0A%0D%0Aconst%20styler%3A%20Styler%20%3D%20(mood)%20%3D%3E%20%7B%0D%0A%0D%0A%7D%0D%0A%2F%2F%20autocomplete%2C%20type%20passing%2C%20no%20non-standard%20properties%0D%0Aconst%20styledExampleOneA%3A%20Partial%3CStyles%3E%20%3D%20%7B%0D%0A%20%20propA%3A%20'a'%2C%0D%0A%20%20propB%3A%20'letter%20b'%0D%0A%7D%0D%0A%0D%0Astyler(styledExampleOneA)%0D%0Astyler(%7B%0D%0A%20%20propA%3A%20'a'%2C%0D%0A%20%20propB%3A%20'letter%20b'%0D%0A%7D)%0D%0A%0D%0A%0D%0A%2F%2F%20autocomplete%2C%20types%20protecting%2C%20non-standard%20properties%0D%0Aconst%20styledExampleOneBa%3A%20Partial%3CStyles%3E%20%3D%20%7B%0D%0A%20%20propA%3A%20'letter%20a'%2C%0D%0A%20%20propB%3A%20'letter%20b'%2C%0D%0A%0D%0A%20%20arbitrary%3A%20%7B%0D%0A%20%20%20%20propA%3A%20'letter%20a'%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Astyler(styledExampleOneBa)%0D%0A%2F%2F%20same%20thing%20passed%20directly%20though%0D%0A%2F%2F%20autocomplete%2C%20types%20protecting%2C%20non-standard%20properties%0D%0Astyler(%7B%0D%0A%20%20propA%3A%20'letter%20a'%2C%0D%0A%20%20propB%3A%20'letter%20b'%2C%0D%0A%0D%0A%20%20arbitrary%3A%20%7B%0D%0A%20%20%20%20propA%3A%20'letter%20a'%0D%0A%20%20%7D%0D%0A%7D)%0D%0A%0D%0Aconst%20badStyleFunctionExample%20%3D%20()%20%3D%3E%20%7B%7D%0D%0A%0D%0Astyler(badStyleFunctionExample)%0D%0Astyler(()%20%3D%3E%20%7B%20%7D)%0D%0A%0D%0A%2F%2F%20autocomplete%2C%20types%20protecting%2C%20non-standard%20properties%0D%0Aconst%20goodStyleFunctionExample%3A%20CorrectStyleFunction%20%3D%20(prop)%20%3D%3E%20(%7B%0D%0A%20%20propA%3A%20'letter%20a'%2C%0D%0A%20%20propB%3A%20'b'%2C%0D%0A%0D%0A%20%20arbitrary%3A%20%7B%0D%0A%20%20%20%20propA%3A%20'letter%20a'%0D%0A%20%20%7D%0D%0A%7D)%0D%0A%0D%0Astyler(goodStyleFunctionExample)%0D%0A%0D%0A%2F%2F%20same%20thing%20passed%20directly%20though%0D%0A%2F%2F%20no%20autocomplete%2C%20types%20protecting%2C%20non-standard%20properties%0D%0Astyler((prop)%20%3D%3E%20(%7B%0D%0A%20%20propA%3A%20'letter%20a'%2C%0D%0A%20%20propB%3A%20'letter%20b'%2C%0D%0A%0D%0A%20%20arbitrary%3A%20%7B%0D%0A%20%20%20%20propA%3A%20'letter%20a'%0D%0A%20%20%7D%0D%0A%7D))%0D%0A%0D%0A%0D%0A%0D%0A)

**Comment by kentcdodds** [comment]
Make sure it can support this too: http://www.typescriptlang.org/play/#src=interface%20StylesComplete%20%7B%0D%0A%20%20propA%3A%20'letter%20a'%20%7C%20'a'%2C%0D%0A%20%20propB%3A%20'letter%20b'%20%7C%20'b'%2C%0D%0A%7D%0D%0A%0D%0Ainterface%20StylesLossy%20%7B%0D%0A%20%20%5Bkey%3A%20string%5D%3A%20string%20%7C%20undefined%20%7C%20Partial%3CStylesComplete%3E%2C%0D%0A%7D%0D%0A%0D%0Atype%20Styles%20%3D%0D%0A%20%20%26%20StylesComplete%0D%0A%20%20%26%20StylesLossy%0D%0A%0D%0Atype%20CorrectStyleFunction%20%3D%0D%0A%20%20(prop%3A%20string)%20%3D%3E%20Partial%3CStyles%3E%0D%0A%0D%0Atype%20LessCorrectButEasierStyleFunction%20%3D%0D%0A%20%20(prop%3A%20string)%20%3D%3E%20Partial%3CStylesComplete%3E%0D%0A%0D%0Ainterface%20Styler%20%7B%0D%0A%20%20(mood%3A%20Partial%3CStyles%3E)%3A%20void%0D%0A%20%20(mood%3A%20CorrectStyleFunction)%3A%20void%0D%0A%7D%0D%0A%0D%0Aconst%20styler%3A%20Styler%20%3D%20(mood)%20%3D%3E%20%7B%0D%0A%0D%0A%7D%0D%0A%2F%2F%20autocomplete%2C%20type%20passing%2C%20no%20non-standard%20properties%0D%0Aconst%20styledExampleOneA%3A%20Partial%3CStyles%3E%20%3D%20%7B%0D%0A%20%20propA%3A%20'a'%2C%0D%0A%20%20propB%3A%20'letter%20b'%0D%0A%7D%0D%0A%0D%0Astyler(styledExampleOneA)%0D%0Astyler(%7B%0D%0A%20%20propA%3A%20'a'%2C%0D%0A%20%20propB%3A%20'letter%20b'%0D%0A%7D)%0D%0A%0D%0A%0D%0A%2F%2F%20autocomplete%2C%20types%20protecting%2C%20non-standard%20properties%0D%0Aconst%20styledExampleOneBa%3A%20Partial%3CStyles%3E%20%3D%20%7B%0D%0A%20%20propA%3A%20'letter%20a'%2C%0D%0A%20%20propB%3A%20'letter%20b'%2C%0D%0A%0D%0A%20%20arbitrary%3A%20%7B%0D%0A%20%20%20%20propA%3A%20'letter%20a'%0D%0A%20%20%7D%0D%0A%7D%0D%0A%0D%0Astyler(styledExampleOneBa)%0D%0A%2F%2F%20same%20thing%20passed%20directly%20though%0D%0A%2F%2F%20autocomplete%2C%20types%20protecting%2C%20non-standard%20properties%0D%0Astyler(%7B%0D%0A%20%20propA%3A%20'letter%20a'%2C%0D%0A%20%20propB%3A%20'letter%20b'%2C%0D%0A%0D%0A%20%20arbitrary%3A%20%7B%0D%0A%20%20%20%20propA%3A%20'letter%20a'%0D%0A%20%20%7D%0D%0A%7D)%0D%0A%0D%0Aconst%20badStyleFunctionExample%20%3D%20()%20%3D%3E%20%7B%7D%0D%0A%0D%0Astyler(badStyleFunctionExample)%0D%0Astyler(()%20%3D%3E%20%7B%20%7D)%0D%0A%0D%0A%2F%2F%20autocomplete%2C%20types%20protecting%2C%20non-standard%20properties%0D%0Aconst%20goodStyleFunctionExample%3A%20CorrectStyleFunction%20%3D%20(prop)%20%3D%3E%20(%7B%0D%0A%20%20propA%3A%20'letter%20a'%2C%0D%0A%20%20propB%3A%20'b'%2C%0D%0A%0D%0A%20%20arbitrary%3A%20%7B%0D%0A%20%20%20%20propA%3A%20'letter%20a'%0D%0A%20%20%7D%0D%0A%7D)%0D%0A%0D%0Astyler(goodStyleFunctionExample)%0D%0A%0D%0A%2F%2F%20same%20thing%20passed%20directly%20though%0D%0A%2F%2F%20no%20autocomplete%2C%20types%20protecting%2C%20non-standard%20properties%0D%0Astyler((prop)%20%3D%3E%20(%7B%0D%0A%20%20propA%3A%20'letter%20a'%2C%0D%0A%20%20propB%3A%20'letter%20b'%2C%0D%0A%0D%0A%20%20arbitrary%3A%20%7B%0D%0A%20%20%20%20propA%3A%20'letter%20a'%0D%0A%20%20%7D%0D%0A%7D))%0D%0A%0D%0A%0D%0A%0D%0A

:smile:

**Comment by luke-john** [comment]
@kentcdodds the link you've shared appears to be the same as mine.

This is likely because the typescript playground can do unexpected things when trying to share edits on a playground someone else created.

To share changed code, I've found the best way is to;

* open www.typescriptlang.org/play/ in a fresh window,
* paste the changes
* click the share button
* make sure `Text buffer too large to share` doesn't appear adjacent to the options button
* share the url

Cheers.

**Comment by kentcdodds** [comment]
Ah, that's rather annoying 🙃 here it is: http://www.typescriptlang.org/play/#src=interface%20StylesComplete%20%7B%0D%0A%20%20propA%3A%20'letter%20a'%20%7C%20'a'%2C%0D%0A%20%20propB%3A%20'letter%20b'%20%7C%20'b'%2C%0D%0A%7D%0D%0A%0D%0Ainterface%20StylesLossy%20%7B%0D%0A%20%20%5Bkey%3A%20string%5D%3A%20string%20%7C%20undefined%20%7C%20Partial%3CStylesComplete%3E%2C%0D%0A%7D%0D%0A%0D%0Atype%20Styles%20%3D%0D%0A%20%20%26%20StylesComplete%0D%0A%20%20%26%20StylesLossy%0D%0A%0D%0Atype%20CorrectStyleFunction%20%3D%0D%0A%20%20(prop%3A%20string)%20%3D%3E%20Partial%3CStyles%3E%0D%0A%0D%0Atype%20LessCorrectButEasierStyleFunction%20%3D%0D%0A%20%20(prop%3A%20string)%20%3D%3E%20Partial%3CStylesComplete%3E%0D%0A%0D%0Ainterface%20Styler%20%7B%0D%0A%20%20(mood%3A%20Partial%3CStyles%3E)%3A%20void%0D%0A%20%20(mood%3A%20CorrectStyleFunction)%3A%20void%0D%0A%7D%0D%0A%0D%0Aconst%20styler%3A%20Styler%20%3D%20(mood)%20%3D%3E%20%7B%0D%0A%0D%0A%7D%0D%0A%0D%0Astyler(()%20%3D%3E%20(%5B%7B%7D%5D))%0D%0Astyler(%5B()%20%3D%3E%20(%5B%7B%7D%5D)%5D)%0D%0Astyler(()%20%3D%3E%20'class-name')%0D%0Astyler(()%20%3D%3E%20%5B'class-name'%5D)%0D%0Astyler(()%20%3D%3E%20%5Bnull%5D)%0D%0A%0D%0A

**Comment by luke-john** [comment]
Awesome, thanks for that.

See below for an update which takes those argument shapes into account.

[typescript playground example](http://www.typescriptlang.org/play/#src=interface%20StylesComplete%20%7B%0D%0A%20%20propA%3A%20'letter%20a'%20%7C%20'a'%2C%0D%0A%20%20propB%3A%20'letter%20b'%20%7C%20'b'%2C%0D%0A%7D%0D%0A%0D%0Ainterface%20StylesLossy%20%7B%0D%0A%20%20%5Bkey%3A%20string%5D%3A%20string%20%7C%20undefined%20%7C%20Partial%3CStylesComplete%3E%2C%0D%0A%7D%0D%0A%0D%0Atype%20Styles%20%3D%0D%0A%20%20%26%20StylesComplete%0D%0A%20%20%26%20StylesLossy%0D%0A%0D%0A%2F%2F%20returns%20styles%20or%20strings%0D%0Ainterface%20StyleFunction%20%7B%0D%0A%20%20(prop%3A%20string)%3A%20Partial%3CStyles%3E%20%7C%20string%0D%0A%7D%20%0D%0A%0D%0A%2F%2F%20returns%20array%20of%20styles%20and%20strings%0D%0Ainterface%20StyleFunctionArray%20%7B%0D%0A%20%20(prop%3A%20string)%3A%20Array%3CPartial%3CStyles%3E%20%7C%20string%20%7C%20StyleFunction%3E%0D%0A%7D%0D%0A%0D%0Atype%20ArrayStyle%20%3D%20Array%3C%0D%0A%20%20%7C%20StyleFunctionArray%0D%0A%20%20%7C%20string%0D%0A%20%20%7C%20Partial%3CStyles%3E%0D%0A%3E%0D%0A%0D%0Atype%20LessCorrectButEasierStyleFunction%20%3D%0D%0A%20%20(prop%3A%20string)%20%3D%3E%20Partial%3CStylesComplete%3E%0D%0A%0D%0Ainterface%20Styler%20%7B%0D%0A%20%20(mood%3A%20Partial%3CStyles%3E)%3A%20void%0D%0A%0D%0A%20%20(mood%3A%20StyleFunction)%3A%20void%0D%0A%20%20(mood%3A%20StyleFunctionArray)%3A%20void%0D%0A%20%20(mood%3A%20ArrayStyle)%3A%20void%0D%0A%20%20%0D%0A%7D%0D%0A%0D%0Aconst%20styler%3A%20Styler%20%3D%20(mood)%20%3D%3E%20%7B%7D%0D%0A%0D%0A%0D%0Astyler(()%20%3D%3E%20(%7B%0D%0A%20%20propA%3A%20'letter%20a'%20as%20'letter%20a'%0D%0A%7D))%0D%0A%0D%0Astyler(()%20%3D%3E%20(%0D%0A%20%20%5B%0D%0A%20%20%20%20%7B%7D%0D%0A%20%20%5D)%0D%0A)%0D%0Astyler(%0D%0A%20%20%5B%0D%0A%20%20%20%20()%20%3D%3E%20(%0D%0A%20%20%20%20%20%20%5B%0D%0A%20%20%20%20%20%20%20%20%7B%7D%0D%0A%20%20%20%20%20%20%5D%0D%0A%20%20%20%20)%0D%0A%20%20%5D%0D%0A)%0D%0A%0D%0A%2F%2F%20should%20pass%0D%0Astyler((props)%20%3D%3E%20'class-name')%0D%0Astyler((props)%20%3D%3E%20(%7B%0D%0A%20%20propA%3A%20'letter%20a'%0D%0A%7D))%0D%0A%0D%0A%2F%2F%20should%20fail%0D%0Astyler((props)%20%3D%3E%20false)%0D%0Astyler((props)%20%3D%3E%20(%7B%0D%0A%20%20propA%3A%20'b'%20as%20'b'%0D%0A%7D))%0D%0A%0D%0A%2F%2F%20should%20pass%0D%0Astyler((props)%20%3D%3E%20%5B%0D%0A%20%20'class-name'%2C%0D%0A%20%20%7B%0D%0A%20%20%20%20propA%3A%20'letter%20a'%20as%20'letter%20a'%0D%0A%20%20%7D%2C%0D%0A%20%20(props)%20%3D%3E%20(%7B%0D%0A%20%20%20%20propA%3A%20'letter%20a'%20as%20'letter%20a'%0D%0A%20%20%7D)%0D%0A%5D)%0D%0A%0D%0A%2F%2F%20should%20fail%0D%0Astyler(()%20%3D%3E%20%5B%0D%0A%20%20false%2C%0D%0A%20%20%7B%0D%0A%20%20%20%20propA%3A%20'letter%20a'%20as%20'letter%20a'%0D%0A%20%20%7D%2C%0D%0A%20%20(props)%20%3D%3E%20(%7B%0D%0A%20%20%20%20propA%3A%20'letter%20a'%20as%20'letter%20a'%0D%0A%20%20%7D)%0D%0A%5D)%0D%0Astyler((props)%20%3D%3E%20%5B%0D%0A%20%20'class-name'%2C%0D%0A%20%20%7B%0D%0A%20%20%20%20propA%3A%20'b'%20as%20'b'%0D%0A%20%20%7D%2C%0D%0A%20%20(props)%20%3D%3E%20(%7B%0D%0A%20%20%20%20propA%3A%20'letter%20a'%20as%20'letter%20a'%0D%0A%20%20%7D)%0D%0A%5D)%0D%0Astyler((props)%20%3D%3E%20%5B%0D%0A%20%20'class-name'%2C%0D%0A%20%20%7B%0D%0A%20%20%20%20propA%3A%20'letter%20a'%20as%20'letter%20a'%0D%0A%20%20%7D%2C%0D%0A%20%20(props)%20%3D%3E%20(%7B%0D%0A%20%20%20%20propA%3A%20'b'%20as%20'b'%0D%0A%20%20%7D)%0D%0A%5D)%0D%0A%0D%0A%0D%0A%2F%2F%20should%20pass%0D%0Astyler(%0D%0A%20%20()%20%3D%3E%20(%0D%0A%20%20%20%20%5B%0D%0A%20%20%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20propA%3A%20'letter%20a'%20as%20'letter%20a'%0D%0A%20%20%20%20%20%20%7D%2C%0D%0A%20%20%20%20%20%20'classname'%0D%0A%20%20%20%20%5D%0D%0A%20%20)%0D%0A)%0D%0A%0D%0A%2F%2F%20should%20fail%0D%0Astyler(%0D%0A%20%20()%20%3D%3E%20(%0D%0A%20%20%20%20%5B%0D%0A%20%20%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20propA%3A%20'b'%20as%20'b'%0D%0A%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%5D%0D%0A%20%20)%0D%0A)%0D%0Astyler(%0D%0A%20%20()%20%3D%3E%20(%0D%0A%20%20%20%20%5B%0D%0A%20%20%20%20%20%20false%0D%0A%20%20%20%20%5D%0D%0A%20%20)%0D%0A)%0D%0Astyler(%0D%0A%20%20()%20%3D%3E%20(%0D%0A%20%20%20%20%5B%0D%0A%20%20%20%20%20%20()%20%3D%3E%20%7B%7D%0D%0A%20%20%20%20%5D%0D%0A%20%20)%0D%0A)%0D%0A%0D%0A%0D%0A%2F%2F%20should%20pass%0D%0Astyler(%0D%0A%20%20%5B%0D%0A%20%20%20%20(props)%20%3D%3E%20(%0D%0A%20%20%20%20%20%20%5B%0D%0A%20%20%20%20%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20propA%3A%20'letter%20a'%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%5D%0D%0A%20%20%20%20)%2C%0D%0A%20%20%20%20'classname'%0D%0A%20%20%5D%0D%0A)%0D%0A%0D%0A%2F%2F%20should%20fail%0D%0Astyler(%0D%0A%20%20%5B%0D%0A%20%20%20%20(props)%20%3D%3E%20(%0D%0A%20%20%20%20%20%20%5B%0D%0A%20%20%20%20%20%20%20%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20propA%3A%20'b'%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%5D%0D%0A%20%20%20%20)%0D%0A%20%20%5D%0D%0A)%0D%0A%2F%2F%20should%20fail%0D%0Astyler(%0D%0A%20%20%5B%0D%0A%20%20%20%20false%0D%0A%20%20%5D%0D%0A))

**Comment by kentcdodds** [comment]
Looks great :+1:

**Pull request merged**
