### PR TITLE
Fix miscellaneous related with type def files

### PR DESCRIPTION
**Pull request by Ailrun**
**What**: fix inconsistency of type def files

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by Ailrun** [comment]
@luke-john Pardon me? No-newline marks are removed, aren't they?

**Comment by luke-john** [comment]
screen shot 2017-08-22 at 7 50 35 am

From the diffs in Files Changed it looks like they've been removed in a number of files.

**Comment by Ailrun** [comment]
@luke-john 
No-newline marks are removed, that's not a problem (at least I believe), so I can't get the problem.
Sorry for my ignorance, and what's your point?

**Comment by luke-john** [comment]
No sorry you're absolutely right.

I was completely misreading the diff, apologies.

**Pull request merged**
