### PR TITLE
SSR implementation

### PR DESCRIPTION
**Pull request by nitin42**
**What**: Server Side Rendering 

**Why**: #134 

**How**: 
* Added `renderStaticMarkup` to collect the html, css and rendered class names (returned by glamor)

**Checklist**:

- [ ] Documentation N/A
- [ ] Tests N/A
- [ ] Code complete
- [ ] Added myself to contributors table 
- [x] Followed the commit message format 

Still needs improvements though !

### CODE REVIEW

**Comment by nitin42** [comment]
Because we collect all of the calls to `css()` internally using glamor, so we have to rely `renderStatic` to return the generated html and css. We may need to rewrite this from scratch if the glamorous API changes in the future.

**Comment by kentcdodds** [comment]
> We may need to rewrite this from scratch if the glamorous API changes in the future.

That's fine 👍 

> Also that `glamor` provides `renderStaticOptimized`, we could add this also to the `StyleSheetServer`.

I think that we should just use `renderStaticOptimized`. I don't see any reason not to do that... 🤔

**Comment by kentcdodds** [comment]
Hmmm.... I was actually refactoring your PR in the GitHub editor and this is what I ended up with:

screen shot 2017-07-04 at 2 09 29 pm

Seems pretty pointless... We're not really doing much... 🤔 I wonder if this is really just a matter of creating more examples 🤔

**Comment by nitin42** [comment]
🤔  I think it does make a point because `Glamorous` is using `glamor` as a peer dependency. For SSR , we need to keep track of all the `css()` calls and since we rely on `glamor`, we can use `renderStaticOptimized` from `glamor` ? Or should we write our own method  ?

**Comment by kentcdodds** [comment]
What I was suggesting is instead just improve our documentation for how to do SSR with glamor (which does now and always will work with glamorous).

**Comment by nitin42** [comment]
Seems better to me. I would create some examples and then we can document it later ?

**Comment by nitin42** [comment]
Good idea 👍 . I could create some examples taking inspiration from styled-components, aphrodite and glamor !

**Comment by kentcdodds** [comment]
Sounds great. I'll go ahead and close this one. Thanks!

**Comment by nitin42** [comment]
Hi there ! I am a little busy maintaining my project [`terminal-in-react`](https://github.com/nitin42/terminal-in-react). I will start working on the examples soon. Cool ?

**Comment by kentcdodds** [comment]
Sounds good! Thanks! Maybe you could just add them directly to the new website: github.com/kentcdodds/glamorous-website

**Comment by nitin42** [comment]
Sure!

**Pull request closed without merging**
