### PR TITLE
Add onInvalid to react props

### PR DESCRIPTION
**Pull request by tvler**
**What**:
Adds `onInvalid` to list of react props to pass through.

**Why**:
`onInvalid` is a supported react event, but it isn't documented on the SyntheticEvent page (https://github.com/facebook/react/pull/10554).

**How**:
Added `onInvalid` to the `react-props.js` array.

**Checklist**:

- [x] Documentation
- [x] Tests
- [x] Ready to be merged 
- [x] Added myself to contributors table

### CODE REVIEW

**Comment by tvler** [comment]
Right now you _can_ pass through `onInvalid` through the `forwardProps` option like this:

``` jsx
glamorous('input', { forwardProps: 'onInvalid' })
```

But I think it'll make more sense to include this in the default component factory:

```jsx
glamorous.input
```

**Comment by kentcdodds** [comment]
Hi @tvler! Thanks for the PR. Is `onInvalid` an officially supported react event callback?

**Comment by tvler** [comment]
Hey! Yep, the event was added in [v15](https://facebook.github.io/react/blog/2016/04/07/react-v15.html) in the PR https://github.com/facebook/react/pull/5187.

**Comment by kentcdodds** [comment]
Thank you so much!

**Comment by tvler** [comment]
No problem! Awesome library btw, iFixit's really diggin it 👍

**Comment by kentcdodds** [comment]
Awesome! Could you add iFixit to the [Users.md](https://github.com/paypal/glamorous/blob/master/other/USERS.md)?

**Pull request merged**
