### PR TITLE
fix(typings): fix typings for dynamic styles

### PR DESCRIPTION
**Pull request by ErikCupal**
**What:**
Fixed Typescript typings for dynamic styles. Explained in #81 

**Why:**
Because Typescript guys love proper typings and intelliSense! No, seriously, using dynamic styles in Typescript is very cumbersome without this fix.

**How:**
I decided to use generics to do this as it seems to be a sensible way. Example usage:
```ts
const MyStyledDiv = glamorous.div<{ noPadding?: boolean }>(
  {
    margin: 1,
  },
  (props) => ({
    padding: props.noPadding ? 0 : 4,
  })
)

<MyStyledDiv />
<MyStyledDiv noPadding />
```

**Disclaimer:**
I hope I didn't mess anything up. This is one of my first pull requests 😀. Thanks @kentcdodds for [this great course](https://egghead.io/lessons/javascript-how-to-create-a-pull-request-on-github?series=how-to-contribute-to-an-open-source-project-on-github).

### CODE REVIEW

**Comment by kentcdodds** [comment]
Would you like to [add yourself](../blob/master/CONTRIBUTING.md#add-yourself-as-a-contributor) to the [contributors table](../#contributors)?

Same question to @luke-john actually 😀

**Comment by ErikCupal** [comment]
@kentcdodds Oh, sure! I'll do it.

**Comment by luke-john** [comment]
lgtm

**Comment by sammkj** [comment]
Nice! LGTM

**Comment by kentcdodds** [comment]
Sucks, looks like there are a few conflicts 😞 Could you fix those? Sorry.

**Comment by ErikCupal** [comment]
😊 should be fine now

**Comment by kentcdodds** [comment]
Hey @ErikCupal, thanks so much for your help! I've added you as a collaborator on the project. Please make sure that you review the CONTRIBUTING.md file (specifically the bit about the commit messages and the git hooks) and familiarize yourself with the code of conduct (we're using [the contributor covenant](http://contributor-covenant.org/)). You might also want to [watch the repo](https://help.github.com/articles/watching-repositories/) to be notified when someone files an issue/PR. Please continue to make PRs as you feel the need (you can make your branches directly on the repo rather than your fork if you want). Thanks! And welcome to the team :)

**Comment by ErikCupal** [comment]
Oh, thanks a lot @kentcdodds 😊. I'll happy to make more contributions.

**Pull request merged**
