### PR TITLE
feat(typescript): Improved theme typing and tests (#160)

### PR DESCRIPTION
**Pull request by kentcdodds**
This is our BREAKING CHANGE branch. Once this is merged, a new major release will go out. What else do we want to group into this?

### CODE REVIEW

**Comment by luke-john** [comment]
The excellent addition to the PR from @ErikCupal actually meant that that change is not really Breaking, but more of a Patch.

Using the new language feature of default types on generics meant that we were able to get typesafety with themes without introducing boilerplate when using components that don't use the theme.

The only additional changes in the commit will only break existing code on an update if they have used glamorous incorrectly.

There may be some other similar changes that would be good to land, any that you're aware of @ErikCupal @sammkj?  I've got a long weekend and was planning on doing some work with glamorous on monday so would be happy to pick anything up then :).

**Comment by kentcdodds** [comment]
Whelp, I'd rather not do a major release anyway, so if you're saying that it's unlikely to break anyone then let's just do a patch release. That ok?

**Comment by ErikCupal** [comment]
Yep, the change is not breaking anymore. I agree with Kent, we should just do a patch release 🙂.

**Comment by luke-john** [comment]
Sounds sensible to me, apologies for the extra work that commit led to for you.

**Comment by kentcdodds** [comment]
I merged this manually to avoid an accidental major release (because GitHub's UI sometimes gets messed up when changing commit messages)

**Pull request closed without merging**
