### PR TITLE
Rename vector logo files to match raster counterparts.

### LINKED ISSUE #366: Vector logos have incorrect file names.
Unless I'm missing something it looks like `full.png` is rendered from `compact.ai` and `compact.png` is rendered from `full.ai`.

glamorous-logo

### PR DESCRIPTION
**Pull request by knpwrs**
Fixes #366.

It looks like I'm not able to run the `add-contributor` script:

```
❯ npm run add-contributor

> glamorous@0.0.0-semantically-released add-contributor /Users/ken/Workspace/github.com/knpwrs/glamorous
> kcd-scripts contributors add

module.js:538
    throw err;
    ^

Error: Cannot find module 'all-contributors-cli/cli'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.resolve (internal/module.js:18:19)
    at Object.<anonymous> (/Users/ken/Workspace/github.com/knpwrs/glamorous/node_modules/kcd-scripts/dist/scripts/contributors.js:7:33)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! glamorous@0.0.0-semantically-released add-contributor: `kcd-scripts contributors add`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the glamorous@0.0.0-semantically-released add-contributor script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ken/.npm/_logs/2018-01-03T15_04_17_273Z-debug.log
zsh: exit 1     npm run add-contributor
```

This appears to be an issue more with `kcd-scripts` than` glamorous`. I was able to run `node node_modules/all-contributors-cli/dist/cli.js` (key part being `dist`) but then the precommit hook fails, so I had to commit with `--no-verify`.

### CODE REVIEW

**Comment by knpwrs** [comment]
The linting failures are unrelated to this PR.

**Comment by kentcdodds** [comment]
Hmmm... Give me a second to upgrade all dependencies. Once I've done that you can [rebase your branch on master](https://egghead.io/lessons/javascript-how-to-rebase-a-git-pull-request-branch) and see if that fixes it. I'll let you know when I've updated the dependencies.

**Comment by kentcdodds** [comment]
Ok! Updates have been pushed. You'll want to rebase your changes and `rm -rf node_modules && npm install`. Don't worry about the README conflicts. Just run `./node_modules/.bin/kcd-scripts contributors generate` and that'll regenerate the contributors table for you, taking care of the conflict.

Thanks!

**Comment by kentcdodds** [comment]
Sorry about the trouble with the old dependencies. I'm glad it's worked out now :)

**Comment by knpwrs** [comment]
No problem. Keep up the awesome work!

**Pull request merged**
